"""Database package for EvaliSense."""
from api.database.session import Base, SessionLocal, engine, get_db, init_db
from api.database.models import (
    Role,
    User,
    Department,
    Section,
    Student,
    Subject,
    TeacherSubject,
    Exam,
    ExamQuestion,
    AnswerScript,
    AnswerAnswer,
    AIEvaluation,
    TeacherAssignment,
    FinalMark,
    ScanIssue,
    Notification,
)

__all__ = [
    "Base",
    "SessionLocal",
    "engine",
    "get_db",
    "init_db",
    "Role",
    "User",
    "Department",
    "Section",
    "Student",
    "Subject",
    "TeacherSubject",
    "Exam",
    "ExamQuestion",
    "AnswerScript",
    "AnswerAnswer",
    "AIEvaluation",
    "TeacherAssignment",
    "FinalMark",
    "ScanIssue",
    "Notification",
]
