"""Schemas package for EvaliSense."""
from api.schemas.auth import LoginRequest, TokenResponse, UserProfileResponse, PasswordChangeRequest
from api.schemas.roles import RoleCreate, RoleUpdate, RoleResponse
from api.schemas.users import UserCreate, UserUpdate, UserResponse
from api.schemas.academic import (
    DepartmentCreate,
    DepartmentUpdate,
    DepartmentResponse,
    SectionCreate,
    SectionUpdate,
    SectionResponse,
    StudentCreate,
    StudentUpdate,
    StudentResponse,
    SubjectCreate,
    SubjectUpdate,
    SubjectResponse,
    TeacherSubjectCreate,
    TeacherSubjectResponse,
    ExamCreate,
    ExamUpdate,
    ExamResponse,
    ExamQuestionCreate,
    ExamQuestionUpdate,
    ExamQuestionResponse,
)
from api.schemas.workflow import (
    AnswerScriptResponse,
    AnswerResponse,
    TeacherReviewSubmit,
    ScanIssueResponse,
    NotificationResponse,
)

__all__ = [
    "LoginRequest",
    "TokenResponse",
    "UserProfileResponse",
    "PasswordChangeRequest",
    "RoleCreate",
    "RoleUpdate",
    "RoleResponse",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "DepartmentCreate",
    "DepartmentUpdate",
    "DepartmentResponse",
    "SectionCreate",
    "SectionUpdate",
    "SectionResponse",
    "StudentCreate",
    "StudentUpdate",
    "StudentResponse",
    "SubjectCreate",
    "SubjectUpdate",
    "SubjectResponse",
    "TeacherSubjectCreate",
    "TeacherSubjectResponse",
    "ExamCreate",
    "ExamUpdate",
    "ExamResponse",
    "ExamQuestionCreate",
    "ExamQuestionUpdate",
    "ExamQuestionResponse",
    "AnswerScriptResponse",
    "AnswerResponse",
    "TeacherReviewSubmit",
    "ScanIssueResponse",
    "NotificationResponse",
]
